// <auto-generated />
using System;
using A_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAL.Migrations
{
    [DbContext(typeof(NahidaShoesDbContext))]
    [Migration("20221121125419_QLi")]
    partial class QLi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChieuCaoDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHangGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChieuCaoDeGiay");

                    b.HasIndex("IdGiay");

                    b.HasIndex("IdHangGiay");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdMauSac", "IdSize", "IdNsx", "IdHangGiay", "IdChieuCaoDeGiay", "IdGiay")
                        .IsUnique();

                    b.ToTable("ChiTietGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b26d7ba4-d939-4105-9aad-22ac4562c76b"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("59d65326-77dc-4f4b-ae6c-a16cb8f820d6"),
                            IdGiay = new Guid("6452c3dc-24a4-4ac5-b336-a850941faf78"),
                            IdHangGiay = new Guid("c5aff94a-a329-45c9-86b2-9ec148b4d21b"),
                            IdMauSac = new Guid("913acd9a-4598-4a39-9713-edab7b94a31a"),
                            IdNsx = new Guid("93809d7f-bcc3-4f7e-a27c-016d838f1cef"),
                            IdSize = new Guid("dd4514d6-9dc8-478b-8a67-da2a610fa75e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("6d3af54c-69c9-404e-9b7f-1f0844da7f4c"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("a85cd38f-fefa-4ece-8723-065babab259c"),
                            IdGiay = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            IdHangGiay = new Guid("0e571279-3ea8-49e6-bff4-bd465f18746e"),
                            IdMauSac = new Guid("913acd9a-4598-4a39-9713-edab7b94a31a"),
                            IdNsx = new Guid("34a3fd77-6691-44e5-9dcf-f87e456c200e"),
                            IdSize = new Guid("1d29a26d-1270-4fb7-8f73-61beab8c8704"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("3b6397f3-6ba3-49bc-bd9f-5e3af0ea1a3a"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("a85cd38f-fefa-4ece-8723-065babab259c"),
                            IdGiay = new Guid("1e248a45-bf0a-4428-8a7d-f62eea4b4bc7"),
                            IdHangGiay = new Guid("c67e9afb-1bd5-4070-9fe3-4da75e9d943c"),
                            IdMauSac = new Guid("913acd9a-4598-4a39-9713-edab7b94a31a"),
                            IdNsx = new Guid("a1822629-d551-4739-9098-34ff018c72d4"),
                            IdSize = new Guid("33518e19-bd23-47dd-9f9c-8010c106638e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("27ec8e79-2389-4533-a473-96ee668cb9fb"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("bed3639d-d336-40d3-a865-36e764747e6f"),
                            IdGiay = new Guid("ce22ecde-84f4-4878-b0a4-5b0a45d49171"),
                            IdHangGiay = new Guid("f532ab82-0997-487a-9b65-d7252a6bd6b1"),
                            IdMauSac = new Guid("64f37a56-0999-4566-9ac1-962f422e7b3a"),
                            IdNsx = new Guid("3c6656ed-37f4-4b04-8977-4949cbf7f7d8"),
                            IdSize = new Guid("4e6b191c-c1bc-4813-b947-adb3da90bb85"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d73aad51-c5c8-4b62-a0f9-a0dcc2de4d15"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1ca5b004-58a3-4eeb-bbf1-0ee43c17fd66"),
                            IdGiay = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            IdHangGiay = new Guid("0e571279-3ea8-49e6-bff4-bd465f18746e"),
                            IdMauSac = new Guid("379e207f-2971-4284-ae53-405a7c2ce7b2"),
                            IdNsx = new Guid("3c6656ed-37f4-4b04-8977-4949cbf7f7d8"),
                            IdSize = new Guid("4e6b191c-c1bc-4813-b947-adb3da90bb85"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("3d6b2ec6-3c17-4803-ab3d-5705eb15ae35"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("bed3639d-d336-40d3-a865-36e764747e6f"),
                            IdGiay = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            IdHangGiay = new Guid("c5aff94a-a329-45c9-86b2-9ec148b4d21b"),
                            IdMauSac = new Guid("5d2ec729-abc4-4afc-82e2-67ee3b4037c8"),
                            IdNsx = new Guid("a1822629-d551-4739-9098-34ff018c72d4"),
                            IdSize = new Guid("33518e19-bd23-47dd-9f9c-8010c106638e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("378fc3d4-9e29-49a6-bb1b-750bacda07d9"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1ca5b004-58a3-4eeb-bbf1-0ee43c17fd66"),
                            IdGiay = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            IdHangGiay = new Guid("c67e9afb-1bd5-4070-9fe3-4da75e9d943c"),
                            IdMauSac = new Guid("64f37a56-0999-4566-9ac1-962f422e7b3a"),
                            IdNsx = new Guid("e92a2212-9dc5-4645-9d3d-9b0c23df755c"),
                            IdSize = new Guid("33518e19-bd23-47dd-9f9c-8010c106638e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("cc527b29-62c6-4341-94ac-ee82e0fca179"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("ccd6114d-65db-4716-a616-7ee6782fcca5"),
                            IdGiay = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            IdHangGiay = new Guid("c5aff94a-a329-45c9-86b2-9ec148b4d21b"),
                            IdMauSac = new Guid("743f085a-e81f-4bf2-85f4-f7ca533f6bf7"),
                            IdNsx = new Guid("93809d7f-bcc3-4f7e-a27c-016d838f1cef"),
                            IdSize = new Guid("2cc73740-6617-47d5-b30f-362f873ce757"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("8e198b25-d379-4c3f-86f8-26496ed0e33f"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1ca5b004-58a3-4eeb-bbf1-0ee43c17fd66"),
                            IdGiay = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            IdHangGiay = new Guid("f532ab82-0997-487a-9b65-d7252a6bd6b1"),
                            IdMauSac = new Guid("5d2ec729-abc4-4afc-82e2-67ee3b4037c8"),
                            IdNsx = new Guid("a1822629-d551-4739-9098-34ff018c72d4"),
                            IdSize = new Guid("2cc73740-6617-47d5-b30f-362f873ce757"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("621ee617-2fbd-4d37-9e1b-748f240be7a0"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1ca5b004-58a3-4eeb-bbf1-0ee43c17fd66"),
                            IdGiay = new Guid("ce22ecde-84f4-4878-b0a4-5b0a45d49171"),
                            IdHangGiay = new Guid("f532ab82-0997-487a-9b65-d7252a6bd6b1"),
                            IdMauSac = new Guid("64f37a56-0999-4566-9ac1-962f422e7b3a"),
                            IdNsx = new Guid("34a3fd77-6691-44e5-9dcf-f87e456c200e"),
                            IdSize = new Guid("dd4514d6-9dc8-478b-8a67-da2a610fa75e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdChiTietGiay", "IdSale")
                        .IsUnique();

                    b.ToTable("ChiTietSale");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPhuongThucThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SoTienThanhToan")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdPhuongThucThanhToan");

                    b.ToTable("ChiTietThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTheLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTheLoai");

                    b.HasIndex("IdChiTietGiay", "IdTheLoai")
                        .IsUnique();

                    b.ToTable("ChiTietTheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichCo")
                        .HasColumnType("int");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKichCo")
                        .IsUnique();

                    b.ToTable("ChieuCaoDeGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ca5b004-58a3-4eeb-bbf1-0ee43c17fd66"),
                            KichCo = 1,
                            MaKichCo = "KC1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("bed3639d-d336-40d3-a865-36e764747e6f"),
                            KichCo = 2,
                            MaKichCo = "KC2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a85cd38f-fefa-4ece-8723-065babab259c"),
                            KichCo = 3,
                            MaKichCo = "KC3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("59d65326-77dc-4f4b-ae6c-a16cb8f820d6"),
                            KichCo = 4,
                            MaKichCo = "KC4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ccd6114d-65db-4716-a616-7ee6782fcca5"),
                            KichCo = 5,
                            MaKichCo = "KC5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaChucVu")
                        .IsUnique();

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18805f52-ed09-4ee0-a4d5-68b19b85dc44"),
                            MaChucVu = "CV1",
                            TenChucVu = "Nhân viên",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCuaHang")
                        .IsUnique();

                    b.ToTable("CuaHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("704dbdf1-65a9-4360-9ea9-ac63513bc351"),
                            DiaChi = "Hà Nội",
                            MaCuaHang = "CH1",
                            TenCuaHang = "Cửa hàng 1",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaDiemTieuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("SoDiem")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.HasIndex("MaDiemTieuDung")
                        .IsUnique();

                    b.ToTable("DiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVienTiepQuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiaoCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("TienDuTru")
                        .HasColumnType("real");

                    b.Property<float>("TienLai")
                        .HasColumnType("real");

                    b.Property<float>("TienPhatSinh")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdNhanVienTiepQuan");

                    b.HasIndex("MaGiaoCa")
                        .IsUnique();

                    b.ToTable("GiaoCa");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiay")
                        .IsUnique();

                    b.ToTable("Giay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6452c3dc-24a4-4ac5-b336-a850941faf78"),
                            MaGiay = "G1",
                            TenGiay = "Giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ce22ecde-84f4-4878-b0a4-5b0a45d49171"),
                            MaGiay = "G2",
                            TenGiay = "Giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("30ded702-9bf9-4719-b1e2-8b7c4c0a2b19"),
                            MaGiay = "G3",
                            TenGiay = "Giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("b6d9ff53-19a5-47f0-b3d2-fcc09bcdd1f8"),
                            MaGiay = "G4",
                            TenGiay = "Giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1e248a45-bf0a-4428-8a7d-f62eea4b4bc7"),
                            MaGiay = "G5",
                            TenGiay = "Giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHangGiay")
                        .IsUnique();

                    b.ToTable("HangGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d89dac1b-0b4f-4481-a284-75e3069783e4"),
                            MaHangGiay = "HG1",
                            TenHangGiay = "Hãng giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("0e571279-3ea8-49e6-bff4-bd465f18746e"),
                            MaHangGiay = "HG2",
                            TenHangGiay = "Hãng giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c5aff94a-a329-45c9-86b2-9ec148b4d21b"),
                            MaHangGiay = "HG3",
                            TenHangGiay = "Hãng giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("f532ab82-0997-487a-9b65-d7252a6bd6b1"),
                            MaHangGiay = "HG4",
                            TenHangGiay = "Hãng giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c67e9afb-1bd5-4070-9fe3-4da75e9d943c"),
                            MaHangGiay = "HG5",
                            TenHangGiay = "Hãng giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiamGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ThoiGianShip")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdChiTietGiay", "IdHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKhachHang")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d269c89-d8a5-41a3-a219-fafc0da1ae5e"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH1",
                            NgaySinh = new DateTime(2022, 11, 21, 19, 54, 18, 727, DateTimeKind.Local).AddTicks(8861),
                            Sdt = "0385922775",
                            SoCCCD = "12345",
                            TenKhachHang = "Khách hàng 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a9e3e082-53ec-4a23-9e0a-d137ac7fd735"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH2",
                            NgaySinh = new DateTime(2022, 11, 21, 19, 54, 18, 727, DateTimeKind.Local).AddTicks(8881),
                            Sdt = "0385922775",
                            SoCCCD = "01234",
                            TenKhachHang = "Khách hàng 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTriQuyDoi")
                        .HasColumnType("real");

                    b.Property<Guid>("IdDiemTieuDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdQuyDoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDiemTieuDung");

                    b.HasIndex("IdQuyDoi");

                    b.HasIndex("IdHoaDon", "IdDiemTieuDung", "IdQuyDoi")
                        .IsUnique();

                    b.ToTable("LichSuDiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaMauSac")
                        .IsUnique();

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("913acd9a-4598-4a39-9713-edab7b94a31a"),
                            MaMauSac = "MS1",
                            TenMauSac = "Màu sắc 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("5d2ec729-abc4-4afc-82e2-67ee3b4037c8"),
                            MaMauSac = "MS2",
                            TenMauSac = "Màu sắc 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("743f085a-e81f-4bf2-85f4-f7ca533f6bf7"),
                            MaMauSac = "MS3",
                            TenMauSac = "Màu sắc 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("64f37a56-0999-4566-9ac1-962f422e7b3a"),
                            MaMauSac = "MS4",
                            TenMauSac = "Màu sắc 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("379e207f-2971-4284-ae53-405a7c2ce7b2"),
                            MaMauSac = "MS5",
                            TenMauSac = "Màu sắc 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<Guid>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuaHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.HasIndex("IdCuaHang");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe7be7ac-9983-438d-8233-0720092b579c"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 0,
                            IdChucVu = new Guid("18805f52-ed09-4ee0-a4d5-68b19b85dc44"),
                            IdCuaHang = new Guid("704dbdf1-65a9-4360-9ea9-ac63513bc351"),
                            MaNhanVien = "NV1",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 11, 21, 19, 54, 18, 727, DateTimeKind.Local).AddTicks(8797),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("8facdc32-9a40-4455-9cb8-7ea43751b9e9"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 1,
                            IdChucVu = new Guid("18805f52-ed09-4ee0-a4d5-68b19b85dc44"),
                            IdCuaHang = new Guid("704dbdf1-65a9-4360-9ea9-ac63513bc351"),
                            MaNhanVien = "NV2",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 11, 21, 19, 54, 18, 727, DateTimeKind.Local).AddTicks(8839),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNsx")
                        .IsUnique();

                    b.ToTable("Nsx");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93809d7f-bcc3-4f7e-a27c-016d838f1cef"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX1",
                            TenNsx = "Nhà sản xuất 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("e92a2212-9dc5-4645-9d3d-9b0c23df755c"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX2",
                            TenNsx = "Nhà sản xuất 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("3c6656ed-37f4-4b04-8977-4949cbf7f7d8"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX3",
                            TenNsx = "Nhà sản xuất 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a1822629-d551-4739-9098-34ff018c72d4"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX4",
                            TenNsx = "Nhà sản xuất 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("34a3fd77-6691-44e5-9dcf-f87e456c200e"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX5",
                            TenNsx = "Nhà sản xuất 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQuyDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TiLeQuyDoi")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyDoi")
                        .IsUnique();

                    b.ToTable("QuyDoi");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LuaChonGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamGia")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSize")
                        .HasColumnType("int");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSize")
                        .IsUnique();

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e6b191c-c1bc-4813-b947-adb3da90bb85"),
                            MaSize = "SZ1",
                            SoSize = 30,
                            TenSize = "Size 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("33518e19-bd23-47dd-9f9c-8010c106638e"),
                            MaSize = "SZ2",
                            SoSize = 31,
                            TenSize = "Size 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1d29a26d-1270-4fb7-8f73-61beab8c8704"),
                            MaSize = "SZ3",
                            SoSize = 32,
                            TenSize = "Size 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("2cc73740-6617-47d5-b30f-362f873ce757"),
                            MaSize = "SZ4",
                            SoSize = 33,
                            TenSize = "Size 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("dd4514d6-9dc8-478b-8a67-da2a610fa75e"),
                            MaSize = "SZ5",
                            SoSize = 34,
                            TenSize = "Size 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanCap");

                    b.HasIndex("MaTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.HasOne("A_DAL.Entities.ChieuCaoDeGiay", "IdChieuCaoDeGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdChieuCaoDeGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Giay", "IdGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HangGiay", "IdHangGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdHangGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Nsx", "IdNsxNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdNsx")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Size", "IdSizeNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSize")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChieuCaoDeGiayNavigation");

                    b.Navigation("IdGiayNavigation");

                    b.Navigation("IdHangGiayNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdNsxNavigation");

                    b.Navigation("IdSizeNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Sale", "IdSaleNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.PhuongThucThanhToan", "IdPhuongThucThanhToanNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdPhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdPhuongThucThanhToanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "KhachHang")
                        .WithOne("DiemTieuDung")
                        .HasForeignKey("A_DAL.Entities.DiemTieuDung", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("GiaoCas")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienTiepQuanNavigation")
                        .WithMany("GiaoCaTiepQuans")
                        .HasForeignKey("IdNhanVienTiepQuan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdNhanVienTiepQuanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.DiemTieuDung", "IdDiemTieuDungNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdDiemTieuDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.QuyDoi", "IdQuyDoiNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdQuyDoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdDiemTieuDungNavigation");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdQuyDoiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("A_DAL.Entities.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.CuaHang", "IdCuaHangNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCuaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChucVuNavigation");

                    b.Navigation("IdCuaHangNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("TheLoais")
                        .HasForeignKey("IdPhanCap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Navigation("ChiTietSales");

                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietThanhToans");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("DiemTieuDung")
                        .IsRequired();

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("GiaoCaTiepQuans");

                    b.Navigation("GiaoCas");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Navigation("ChiTietSales");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("TheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
