// <auto-generated />
using System;
using A_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAL.Migrations
{
    [DbContext(typeof(NahidaShoesDbContext))]
    [Migration("20221119171047_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChieuCaoDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHangGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChieuCaoDeGiay");

                    b.HasIndex("IdGiay");

                    b.HasIndex("IdHangGiay");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdMauSac", "IdSize", "IdNsx", "IdHangGiay", "IdChieuCaoDeGiay", "IdGiay")
                        .IsUnique();

                    b.ToTable("ChiTietGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8031056d-96d9-40a1-be52-e1feef96841c"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("38bd722d-023f-4a48-9105-cb5e87c409b1"),
                            IdGiay = new Guid("a5f8f594-1c9f-4b6c-bcb4-0d3fb60f7946"),
                            IdHangGiay = new Guid("124e683f-3522-4e73-b064-ea30e556f89f"),
                            IdMauSac = new Guid("633c4457-b963-4c07-a024-cdcb8d96e7ee"),
                            IdNsx = new Guid("a9138c09-1c53-4574-bd58-e75539014705"),
                            IdSize = new Guid("aaea18eb-0532-424d-bbdc-e6acc7475944"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("835a0466-91e1-4b4a-b4f9-d67de95451d3"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("06361cd3-c564-404f-b8c6-fefa457c43c1"),
                            IdGiay = new Guid("ff9226ce-2856-4b3f-8242-b12735e28b8a"),
                            IdHangGiay = new Guid("801094c8-681f-4ac9-9516-afd228b145bb"),
                            IdMauSac = new Guid("d9a01027-ab98-4965-a1a9-ee40c2d6bd0b"),
                            IdNsx = new Guid("9323e410-23ca-437f-877a-43f72119fdfe"),
                            IdSize = new Guid("3acd5847-3e35-4841-ab52-c66e082c604d"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("5c8c1052-bfd6-46b2-87bb-775592948f56"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("8ba64401-0ef9-4871-9361-f445b202a533"),
                            IdGiay = new Guid("719e3ab9-0572-4c13-a66e-81dd022482f4"),
                            IdHangGiay = new Guid("f78b6b34-cf4e-47ec-ad81-038ac0556e2b"),
                            IdMauSac = new Guid("d9607d14-fbd2-499b-875b-615d7a0cbcfd"),
                            IdNsx = new Guid("a9138c09-1c53-4574-bd58-e75539014705"),
                            IdSize = new Guid("51496538-8e5b-467c-bc4d-00fd83f25d2c"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("5963bfa5-14f1-4513-a1f2-f538d5868e88"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("38bd722d-023f-4a48-9105-cb5e87c409b1"),
                            IdGiay = new Guid("a5f8f594-1c9f-4b6c-bcb4-0d3fb60f7946"),
                            IdHangGiay = new Guid("2420bf5b-4113-4fe9-a193-a8dc52d9663c"),
                            IdMauSac = new Guid("d9a01027-ab98-4965-a1a9-ee40c2d6bd0b"),
                            IdNsx = new Guid("a9138c09-1c53-4574-bd58-e75539014705"),
                            IdSize = new Guid("1cef9eeb-c70d-4210-a3be-446ad2f528b0"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c464c12c-2669-482a-811b-d51848fa0999"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("49ae44a8-5857-49cf-97f2-48e6c68c82ea"),
                            IdGiay = new Guid("ff9226ce-2856-4b3f-8242-b12735e28b8a"),
                            IdHangGiay = new Guid("f78b6b34-cf4e-47ec-ad81-038ac0556e2b"),
                            IdMauSac = new Guid("d9a01027-ab98-4965-a1a9-ee40c2d6bd0b"),
                            IdNsx = new Guid("2aeea779-8c6f-4b06-ba5b-923b158fe5e8"),
                            IdSize = new Guid("53baed26-560b-4d3b-9f8d-831cfd67a57e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("16bcc805-726e-480d-8dcd-89a624aafb3f"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("2e9e1928-904d-4729-91ef-f1de54a4fed0"),
                            IdGiay = new Guid("a5f8f594-1c9f-4b6c-bcb4-0d3fb60f7946"),
                            IdHangGiay = new Guid("f78b6b34-cf4e-47ec-ad81-038ac0556e2b"),
                            IdMauSac = new Guid("d9607d14-fbd2-499b-875b-615d7a0cbcfd"),
                            IdNsx = new Guid("07b60a5c-2968-4dd9-8a9b-ef3f0b7b4098"),
                            IdSize = new Guid("53baed26-560b-4d3b-9f8d-831cfd67a57e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("b4620007-b639-4a1f-92ff-5cff9374574d"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("38bd722d-023f-4a48-9105-cb5e87c409b1"),
                            IdGiay = new Guid("a5f8f594-1c9f-4b6c-bcb4-0d3fb60f7946"),
                            IdHangGiay = new Guid("801094c8-681f-4ac9-9516-afd228b145bb"),
                            IdMauSac = new Guid("633c4457-b963-4c07-a024-cdcb8d96e7ee"),
                            IdNsx = new Guid("a455b087-0860-4bd7-934f-27074e3acff8"),
                            IdSize = new Guid("51496538-8e5b-467c-bc4d-00fd83f25d2c"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d12e0395-7b29-4d3f-be34-e4a1cff56ffc"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("38bd722d-023f-4a48-9105-cb5e87c409b1"),
                            IdGiay = new Guid("6f13da20-807e-4f3f-b162-157d74f5905d"),
                            IdHangGiay = new Guid("801094c8-681f-4ac9-9516-afd228b145bb"),
                            IdMauSac = new Guid("35b0d6fd-582f-4b7e-92f9-a6edf4b6e344"),
                            IdNsx = new Guid("07b60a5c-2968-4dd9-8a9b-ef3f0b7b4098"),
                            IdSize = new Guid("51496538-8e5b-467c-bc4d-00fd83f25d2c"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("3ec21f6e-94b8-4dbf-be1e-d8ae0f88ac7d"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("2e9e1928-904d-4729-91ef-f1de54a4fed0"),
                            IdGiay = new Guid("9d6534fc-d052-42ce-b0ca-25b754df5d08"),
                            IdHangGiay = new Guid("f78b6b34-cf4e-47ec-ad81-038ac0556e2b"),
                            IdMauSac = new Guid("27134929-72c2-404b-8e74-68cc1bb809c7"),
                            IdNsx = new Guid("9323e410-23ca-437f-877a-43f72119fdfe"),
                            IdSize = new Guid("aaea18eb-0532-424d-bbdc-e6acc7475944"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("58d1119e-1607-4dd2-8fc8-3a052a616bc4"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("38bd722d-023f-4a48-9105-cb5e87c409b1"),
                            IdGiay = new Guid("9d6534fc-d052-42ce-b0ca-25b754df5d08"),
                            IdHangGiay = new Guid("2420bf5b-4113-4fe9-a193-a8dc52d9663c"),
                            IdMauSac = new Guid("35b0d6fd-582f-4b7e-92f9-a6edf4b6e344"),
                            IdNsx = new Guid("a455b087-0860-4bd7-934f-27074e3acff8"),
                            IdSize = new Guid("53baed26-560b-4d3b-9f8d-831cfd67a57e"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdChiTietGiay", "IdSale")
                        .IsUnique();

                    b.ToTable("ChiTietSale");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPhuongThucThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SoTienThanhToan")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdPhuongThucThanhToan");

                    b.ToTable("ChiTietThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTheLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTheLoai");

                    b.HasIndex("IdChiTietGiay", "IdTheLoai")
                        .IsUnique();

                    b.ToTable("ChiTietTheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichCo")
                        .HasColumnType("int");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKichCo")
                        .IsUnique();

                    b.ToTable("ChieuCaoDeGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06361cd3-c564-404f-b8c6-fefa457c43c1"),
                            KichCo = 1,
                            MaKichCo = "KC1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("2e9e1928-904d-4729-91ef-f1de54a4fed0"),
                            KichCo = 2,
                            MaKichCo = "KC2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("8ba64401-0ef9-4871-9361-f445b202a533"),
                            KichCo = 3,
                            MaKichCo = "KC3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("49ae44a8-5857-49cf-97f2-48e6c68c82ea"),
                            KichCo = 4,
                            MaKichCo = "KC4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("38bd722d-023f-4a48-9105-cb5e87c409b1"),
                            KichCo = 5,
                            MaKichCo = "KC5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaChucVu")
                        .IsUnique();

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49befd3e-c1f8-4c00-9449-c303fd9d9e14"),
                            MaChucVu = "CV1",
                            TenChucVu = "Nhân viên",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCuaHang")
                        .IsUnique();

                    b.ToTable("CuaHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bfd5f1e-213a-4df4-b590-fbc575f0f1a7"),
                            DiaChi = "Hà Nội",
                            MaCuaHang = "CH1",
                            TenCuaHang = "Cửa hàng 1",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaDiemTieuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("SoDiem")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.HasIndex("MaDiemTieuDung")
                        .IsUnique();

                    b.ToTable("DiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVienTiepQuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiaoCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("TienDuTru")
                        .HasColumnType("real");

                    b.Property<float>("TienLai")
                        .HasColumnType("real");

                    b.Property<float>("TienPhatSinh")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdNhanVienTiepQuan");

                    b.HasIndex("MaGiaoCa")
                        .IsUnique();

                    b.ToTable("GiaoCa");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiay")
                        .IsUnique();

                    b.ToTable("Giay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f13da20-807e-4f3f-b162-157d74f5905d"),
                            MaGiay = "G1",
                            TenGiay = "Giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a5f8f594-1c9f-4b6c-bcb4-0d3fb60f7946"),
                            MaGiay = "G2",
                            TenGiay = "Giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ff9226ce-2856-4b3f-8242-b12735e28b8a"),
                            MaGiay = "G3",
                            TenGiay = "Giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("719e3ab9-0572-4c13-a66e-81dd022482f4"),
                            MaGiay = "G4",
                            TenGiay = "Giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("9d6534fc-d052-42ce-b0ca-25b754df5d08"),
                            MaGiay = "G5",
                            TenGiay = "Giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHangGiay")
                        .IsUnique();

                    b.ToTable("HangGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2420bf5b-4113-4fe9-a193-a8dc52d9663c"),
                            MaHangGiay = "HG1",
                            TenHangGiay = "Hãng giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("38866392-9646-49ab-8849-dd6b503c5ec7"),
                            MaHangGiay = "HG2",
                            TenHangGiay = "Hãng giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("124e683f-3522-4e73-b064-ea30e556f89f"),
                            MaHangGiay = "HG3",
                            TenHangGiay = "Hãng giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("f78b6b34-cf4e-47ec-ad81-038ac0556e2b"),
                            MaHangGiay = "HG4",
                            TenHangGiay = "Hãng giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("801094c8-681f-4ac9-9516-afd228b145bb"),
                            MaHangGiay = "HG5",
                            TenHangGiay = "Hãng giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiamGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdChiTietGiay", "IdHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKhachHang")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27a4edfc-0d7c-4269-9770-d8e609944281"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH1",
                            NgaySinh = new DateTime(2022, 11, 19, 9, 10, 47, 235, DateTimeKind.Local).AddTicks(3761),
                            Sdt = "0385922775",
                            SoCCCD = "12345",
                            TenKhachHang = "Khách hàng 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("8fb605be-f83a-4c5f-978a-2d3b28102e3e"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH2",
                            NgaySinh = new DateTime(2022, 11, 19, 9, 10, 47, 235, DateTimeKind.Local).AddTicks(3774),
                            Sdt = "0385922775",
                            SoCCCD = "01234",
                            TenKhachHang = "Khách hàng 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTriQuyDoi")
                        .HasColumnType("real");

                    b.Property<Guid>("IdDiemTieuDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdQuyDoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDiemTieuDung");

                    b.HasIndex("IdQuyDoi");

                    b.HasIndex("IdHoaDon", "IdDiemTieuDung", "IdQuyDoi")
                        .IsUnique();

                    b.ToTable("LichSuDiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaMauSac")
                        .IsUnique();

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27134929-72c2-404b-8e74-68cc1bb809c7"),
                            MaMauSac = "MS1",
                            TenMauSac = "Màu sắc 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d9a01027-ab98-4965-a1a9-ee40c2d6bd0b"),
                            MaMauSac = "MS2",
                            TenMauSac = "Màu sắc 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d9607d14-fbd2-499b-875b-615d7a0cbcfd"),
                            MaMauSac = "MS3",
                            TenMauSac = "Màu sắc 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("633c4457-b963-4c07-a024-cdcb8d96e7ee"),
                            MaMauSac = "MS4",
                            TenMauSac = "Màu sắc 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("35b0d6fd-582f-4b7e-92f9-a6edf4b6e344"),
                            MaMauSac = "MS5",
                            TenMauSac = "Màu sắc 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<Guid>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuaHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.HasIndex("IdCuaHang");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ccb52f9-c60b-4a62-b88c-51784829c60a"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 0,
                            IdChucVu = new Guid("49befd3e-c1f8-4c00-9449-c303fd9d9e14"),
                            IdCuaHang = new Guid("6bfd5f1e-213a-4df4-b590-fbc575f0f1a7"),
                            MaNhanVien = "NV1",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 11, 19, 9, 10, 47, 235, DateTimeKind.Local).AddTicks(3689),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("9019c848-4415-4ebc-8584-f7eff34af498"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 1,
                            IdChucVu = new Guid("49befd3e-c1f8-4c00-9449-c303fd9d9e14"),
                            IdCuaHang = new Guid("6bfd5f1e-213a-4df4-b590-fbc575f0f1a7"),
                            MaNhanVien = "NV2",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 11, 19, 9, 10, 47, 235, DateTimeKind.Local).AddTicks(3742),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNsx")
                        .IsUnique();

                    b.ToTable("Nsx");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07b60a5c-2968-4dd9-8a9b-ef3f0b7b4098"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX1",
                            TenNsx = "Nhà sản xuất 1"
                        },
                        new
                        {
                            Id = new Guid("2aeea779-8c6f-4b06-ba5b-923b158fe5e8"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX2",
                            TenNsx = "Nhà sản xuất 2"
                        },
                        new
                        {
                            Id = new Guid("a455b087-0860-4bd7-934f-27074e3acff8"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX3",
                            TenNsx = "Nhà sản xuất 3"
                        },
                        new
                        {
                            Id = new Guid("9323e410-23ca-437f-877a-43f72119fdfe"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX4",
                            TenNsx = "Nhà sản xuất 4"
                        },
                        new
                        {
                            Id = new Guid("a9138c09-1c53-4574-bd58-e75539014705"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX5",
                            TenNsx = "Nhà sản xuất 5"
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQuyDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TiLeQuyDoi")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyDoi")
                        .IsUnique();

                    b.ToTable("QuyDoi");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LuaChonGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamGia")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSize")
                        .HasColumnType("int");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSize")
                        .IsUnique();

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53baed26-560b-4d3b-9f8d-831cfd67a57e"),
                            MaSize = "SZ1",
                            SoSize = 30,
                            TenSize = "Size 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("aaea18eb-0532-424d-bbdc-e6acc7475944"),
                            MaSize = "SZ2",
                            SoSize = 31,
                            TenSize = "Size 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("51496538-8e5b-467c-bc4d-00fd83f25d2c"),
                            MaSize = "SZ3",
                            SoSize = 32,
                            TenSize = "Size 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("3acd5847-3e35-4841-ab52-c66e082c604d"),
                            MaSize = "SZ4",
                            SoSize = 33,
                            TenSize = "Size 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1cef9eeb-c70d-4210-a3be-446ad2f528b0"),
                            MaSize = "SZ5",
                            SoSize = 34,
                            TenSize = "Size 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanCap");

                    b.HasIndex("MaTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.HasOne("A_DAL.Entities.ChieuCaoDeGiay", "IdChieuCaoDeGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdChieuCaoDeGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Giay", "IdGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HangGiay", "IdHangGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdHangGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Nsx", "IdNsxNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdNsx")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Size", "IdSizeNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSize")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChieuCaoDeGiayNavigation");

                    b.Navigation("IdGiayNavigation");

                    b.Navigation("IdHangGiayNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdNsxNavigation");

                    b.Navigation("IdSizeNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Sale", "IdSaleNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.PhuongThucThanhToan", "IdPhuongThucThanhToanNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdPhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdPhuongThucThanhToanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "KhachHang")
                        .WithOne("DiemTieuDung")
                        .HasForeignKey("A_DAL.Entities.DiemTieuDung", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("GiaoCas")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienTiepQuanNavigation")
                        .WithMany("GiaoCaTiepQuans")
                        .HasForeignKey("IdNhanVienTiepQuan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdNhanVienTiepQuanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.DiemTieuDung", "IdDiemTieuDungNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdDiemTieuDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.QuyDoi", "IdQuyDoiNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdQuyDoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdDiemTieuDungNavigation");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdQuyDoiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("A_DAL.Entities.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.CuaHang", "IdCuaHangNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCuaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChucVuNavigation");

                    b.Navigation("IdCuaHangNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("TheLoais")
                        .HasForeignKey("IdPhanCap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Navigation("ChiTietSales");

                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietThanhToans");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("DiemTieuDung")
                        .IsRequired();

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("GiaoCaTiepQuans");

                    b.Navigation("GiaoCas");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Navigation("ChiTietSales");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("TheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
