// <auto-generated />
using System;
using A_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAL.Migrations
{
    [DbContext(typeof(NahidaShoesDbContext))]
    partial class NahidaShoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Anh")
                        .HasColumnType("image");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChieuCaoDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHangGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChieuCaoDeGiay");

                    b.HasIndex("IdGiay");

                    b.HasIndex("IdHangGiay");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdMauSac", "IdSize", "IdNsx", "IdHangGiay", "IdChieuCaoDeGiay", "IdGiay")
                        .IsUnique();

                    b.ToTable("ChiTietGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5312df2-9c89-40c7-8e15-d5bf176c2542"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("52f061d9-abd8-4471-a1b9-a28341746434"),
                            IdGiay = new Guid("962eff7a-7048-4c4e-8703-7e159113017c"),
                            IdHangGiay = new Guid("24fac628-1848-4963-ac09-bc001e483880"),
                            IdMauSac = new Guid("64cf5458-8066-4d6e-8e09-9d932f2e21c3"),
                            IdNsx = new Guid("37c1cc1c-37c2-4036-ab65-2d54d7bb2005"),
                            IdSize = new Guid("71536848-3988-446e-9a24-b3590dd95471"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1d7f1f8b-7f73-4042-8daa-c0a3886915d7"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("2b816b30-35e6-401a-bbd1-2d32ef542d4b"),
                            IdGiay = new Guid("f515a563-7761-448a-9f42-1e77d64629cb"),
                            IdHangGiay = new Guid("792463d5-e845-493a-a57e-d31ccf703de1"),
                            IdMauSac = new Guid("9348c420-82c2-4de6-8d13-380d51d97b81"),
                            IdNsx = new Guid("37c1cc1c-37c2-4036-ab65-2d54d7bb2005"),
                            IdSize = new Guid("566b0322-5d38-40cf-ab89-71d29da26a97"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("46f761a0-4468-41e2-bd42-23be07709e2b"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("2b816b30-35e6-401a-bbd1-2d32ef542d4b"),
                            IdGiay = new Guid("b487143d-db2f-4ba8-8a99-b01996ff0f53"),
                            IdHangGiay = new Guid("24fac628-1848-4963-ac09-bc001e483880"),
                            IdMauSac = new Guid("9348c420-82c2-4de6-8d13-380d51d97b81"),
                            IdNsx = new Guid("f6b20fff-52d7-4dbb-9a05-b3c6d4bc49a7"),
                            IdSize = new Guid("566b0322-5d38-40cf-ab89-71d29da26a97"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("6cd292ce-c14f-446b-a8bf-2c9e146f7fde"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("2b816b30-35e6-401a-bbd1-2d32ef542d4b"),
                            IdGiay = new Guid("51f9fbd5-6e60-44cb-897e-b611a411c604"),
                            IdHangGiay = new Guid("792463d5-e845-493a-a57e-d31ccf703de1"),
                            IdMauSac = new Guid("3c2cb7b4-a5a9-4a87-80dd-fd5e8ec8aef1"),
                            IdNsx = new Guid("1e7ecd25-1c3d-4b63-80af-7dabc6c58a29"),
                            IdSize = new Guid("566b0322-5d38-40cf-ab89-71d29da26a97"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("aa722439-75ba-4296-bd21-d5cee37e9ae0"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1f3a2463-fab8-409c-8e15-6c78d5b72436"),
                            IdGiay = new Guid("b487143d-db2f-4ba8-8a99-b01996ff0f53"),
                            IdHangGiay = new Guid("24fac628-1848-4963-ac09-bc001e483880"),
                            IdMauSac = new Guid("665c3acd-5c1c-4c0f-b37d-f3c7dd66e64c"),
                            IdNsx = new Guid("37c1cc1c-37c2-4036-ab65-2d54d7bb2005"),
                            IdSize = new Guid("566b0322-5d38-40cf-ab89-71d29da26a97"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("4c4c9c04-fdd8-482c-b103-55c3c01f9a46"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("52f061d9-abd8-4471-a1b9-a28341746434"),
                            IdGiay = new Guid("51f9fbd5-6e60-44cb-897e-b611a411c604"),
                            IdHangGiay = new Guid("f85d7d88-4e8e-4ce6-9d29-f88b02529ddd"),
                            IdMauSac = new Guid("64cf5458-8066-4d6e-8e09-9d932f2e21c3"),
                            IdNsx = new Guid("51485847-db73-4706-8af4-14b921baa2c7"),
                            IdSize = new Guid("8a45dba6-0b3b-4590-8b6f-b9443b0ac608"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("02a4c61e-664b-4db7-b145-dc573d3d28cc"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1f3a2463-fab8-409c-8e15-6c78d5b72436"),
                            IdGiay = new Guid("962eff7a-7048-4c4e-8703-7e159113017c"),
                            IdHangGiay = new Guid("c98c52ce-86fe-4c52-9a23-abc33bb6365f"),
                            IdMauSac = new Guid("9348c420-82c2-4de6-8d13-380d51d97b81"),
                            IdNsx = new Guid("1e7ecd25-1c3d-4b63-80af-7dabc6c58a29"),
                            IdSize = new Guid("8a45dba6-0b3b-4590-8b6f-b9443b0ac608"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("e1f1e38a-2466-43ef-ae71-1402b764d502"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1e8fd184-c889-4e2c-a567-10f8b06b3ed3"),
                            IdGiay = new Guid("b487143d-db2f-4ba8-8a99-b01996ff0f53"),
                            IdHangGiay = new Guid("792463d5-e845-493a-a57e-d31ccf703de1"),
                            IdMauSac = new Guid("665c3acd-5c1c-4c0f-b37d-f3c7dd66e64c"),
                            IdNsx = new Guid("f6b20fff-52d7-4dbb-9a05-b3c6d4bc49a7"),
                            IdSize = new Guid("566b0322-5d38-40cf-ab89-71d29da26a97"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ebaa0b4d-3d17-42c4-aa2a-2dec6c251b2a"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("1e8fd184-c889-4e2c-a567-10f8b06b3ed3"),
                            IdGiay = new Guid("b487143d-db2f-4ba8-8a99-b01996ff0f53"),
                            IdHangGiay = new Guid("c98c52ce-86fe-4c52-9a23-abc33bb6365f"),
                            IdMauSac = new Guid("64cf5458-8066-4d6e-8e09-9d932f2e21c3"),
                            IdNsx = new Guid("eaa1f0ff-67f7-4e3e-974b-6922503adf46"),
                            IdSize = new Guid("8a45dba6-0b3b-4590-8b6f-b9443b0ac608"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a3c6f29d-c068-49bf-b3ea-026c0fe6662d"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("dcee0b91-156b-47a2-a295-e580a57b8755"),
                            IdGiay = new Guid("f515a563-7761-448a-9f42-1e77d64629cb"),
                            IdHangGiay = new Guid("24fac628-1848-4963-ac09-bc001e483880"),
                            IdMauSac = new Guid("665c3acd-5c1c-4c0f-b37d-f3c7dd66e64c"),
                            IdNsx = new Guid("eaa1f0ff-67f7-4e3e-974b-6922503adf46"),
                            IdSize = new Guid("547a2588-be59-4d4c-b9e4-d5b47ba84fdb"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdChiTietGiay", "IdSale")
                        .IsUnique();

                    b.ToTable("ChiTietSale");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPhuongThucThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SoTienThanhToan")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdPhuongThucThanhToan");

                    b.ToTable("ChiTietThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTheLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTheLoai");

                    b.HasIndex("IdChiTietGiay", "IdTheLoai")
                        .IsUnique();

                    b.ToTable("ChiTietTheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichCo")
                        .HasColumnType("int");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKichCo")
                        .IsUnique();

                    b.ToTable("ChieuCaoDeGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52f061d9-abd8-4471-a1b9-a28341746434"),
                            KichCo = 1,
                            MaKichCo = "KC1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("2b816b30-35e6-401a-bbd1-2d32ef542d4b"),
                            KichCo = 2,
                            MaKichCo = "KC2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1f3a2463-fab8-409c-8e15-6c78d5b72436"),
                            KichCo = 3,
                            MaKichCo = "KC3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("dcee0b91-156b-47a2-a295-e580a57b8755"),
                            KichCo = 4,
                            MaKichCo = "KC4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1e8fd184-c889-4e2c-a567-10f8b06b3ed3"),
                            KichCo = 5,
                            MaKichCo = "KC5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaChucVu")
                        .IsUnique();

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11a7cd9d-cf59-427a-8586-b4bf6c904d7a"),
                            MaChucVu = "CV1",
                            TenChucVu = "Nhân viên",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCuaHang")
                        .IsUnique();

                    b.ToTable("CuaHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ef777f2-5086-4a26-937b-b51d51955bc7"),
                            DiaChi = "Hà Nội",
                            MaCuaHang = "CH1",
                            TenCuaHang = "Cửa hàng 1",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaDiemTieuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("SoDiem")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.HasIndex("MaDiemTieuDung")
                        .IsUnique();

                    b.ToTable("DiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVienTiepQuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiaoCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("TienDuTru")
                        .HasColumnType("real");

                    b.Property<float>("TienLai")
                        .HasColumnType("real");

                    b.Property<float>("TienPhatSinh")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdNhanVienTiepQuan");

                    b.HasIndex("MaGiaoCa")
                        .IsUnique();

                    b.ToTable("GiaoCa");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiay")
                        .IsUnique();

                    b.ToTable("Giay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f515a563-7761-448a-9f42-1e77d64629cb"),
                            MaGiay = "G1",
                            TenGiay = "Giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("51f9fbd5-6e60-44cb-897e-b611a411c604"),
                            MaGiay = "G2",
                            TenGiay = "Giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("b487143d-db2f-4ba8-8a99-b01996ff0f53"),
                            MaGiay = "G3",
                            TenGiay = "Giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("962eff7a-7048-4c4e-8703-7e159113017c"),
                            MaGiay = "G4",
                            TenGiay = "Giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("5975ba59-f7bb-4d47-946f-7f9dbc2bee3f"),
                            MaGiay = "G5",
                            TenGiay = "Giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHangGiay")
                        .IsUnique();

                    b.ToTable("HangGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("248a42ea-5924-4496-bc6b-029daef335a3"),
                            MaHangGiay = "HG1",
                            TenHangGiay = "Hãng giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c98c52ce-86fe-4c52-9a23-abc33bb6365f"),
                            MaHangGiay = "HG2",
                            TenHangGiay = "Hãng giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("792463d5-e845-493a-a57e-d31ccf703de1"),
                            MaHangGiay = "HG3",
                            TenHangGiay = "Hãng giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("24fac628-1848-4963-ac09-bc001e483880"),
                            MaHangGiay = "HG4",
                            TenHangGiay = "Hãng giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("f85d7d88-4e8e-4ce6-9d29-f88b02529ddd"),
                            MaHangGiay = "HG5",
                            TenHangGiay = "Hãng giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiamGia")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhuongThucMua")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianShip")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongSoTien")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdChiTietGiay", "IdHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKhachHang")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8b58bc7-ba15-49df-99d5-0d1dff5f0227"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH1",
                            NgaySinh = new DateTime(2022, 12, 9, 20, 24, 50, 168, DateTimeKind.Local).AddTicks(1900),
                            Sdt = "0385922775",
                            SoCCCD = "12345",
                            TenKhachHang = "Khách hàng 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ba1c37d5-8df3-4081-b38f-171933771026"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH2",
                            NgaySinh = new DateTime(2022, 12, 9, 20, 24, 50, 168, DateTimeKind.Local).AddTicks(1922),
                            Sdt = "0385922775",
                            SoCCCD = "01234",
                            TenKhachHang = "Khách hàng 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTriQuyDoi")
                        .HasColumnType("real");

                    b.Property<Guid>("IdDiemTieuDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdQuyDoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDiemTieuDung");

                    b.HasIndex("IdQuyDoi");

                    b.HasIndex("IdHoaDon", "IdDiemTieuDung", "IdQuyDoi")
                        .IsUnique();

                    b.ToTable("LichSuDiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaMauSac")
                        .IsUnique();

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c2cb7b4-a5a9-4a87-80dd-fd5e8ec8aef1"),
                            MaMauSac = "MS1",
                            TenMauSac = "Màu sắc 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("64cf5458-8066-4d6e-8e09-9d932f2e21c3"),
                            MaMauSac = "MS2",
                            TenMauSac = "Màu sắc 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("9348c420-82c2-4de6-8d13-380d51d97b81"),
                            MaMauSac = "MS3",
                            TenMauSac = "Màu sắc 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("fbabd7c0-de2b-403c-bd34-b6f44d57d7ab"),
                            MaMauSac = "MS4",
                            TenMauSac = "Màu sắc 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("665c3acd-5c1c-4c0f-b37d-f3c7dd66e64c"),
                            MaMauSac = "MS5",
                            TenMauSac = "Màu sắc 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<Guid>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuaHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.HasIndex("IdCuaHang");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a19f6d-1b26-4b9c-a870-1e16fcf62a74"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 0,
                            IdChucVu = new Guid("11a7cd9d-cf59-427a-8586-b4bf6c904d7a"),
                            IdCuaHang = new Guid("9ef777f2-5086-4a26-937b-b51d51955bc7"),
                            MaNhanVien = "NV1",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 12, 9, 20, 24, 50, 168, DateTimeKind.Local).AddTicks(1831),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("2da6b300-bc31-46c4-8075-d0ae21bfb6c9"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 1,
                            IdChucVu = new Guid("11a7cd9d-cf59-427a-8586-b4bf6c904d7a"),
                            IdCuaHang = new Guid("9ef777f2-5086-4a26-937b-b51d51955bc7"),
                            MaNhanVien = "NV2",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 12, 9, 20, 24, 50, 168, DateTimeKind.Local).AddTicks(1879),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNsx")
                        .IsUnique();

                    b.ToTable("Nsx");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6b20fff-52d7-4dbb-9a05-b3c6d4bc49a7"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX1",
                            TenNsx = "Nhà sản xuất 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("eaa1f0ff-67f7-4e3e-974b-6922503adf46"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX2",
                            TenNsx = "Nhà sản xuất 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("37c1cc1c-37c2-4036-ab65-2d54d7bb2005"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX3",
                            TenNsx = "Nhà sản xuất 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1e7ecd25-1c3d-4b63-80af-7dabc6c58a29"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX4",
                            TenNsx = "Nhà sản xuất 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("51485847-db73-4706-8af4-14b921baa2c7"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX5",
                            TenNsx = "Nhà sản xuất 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQuyDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TiLeQuyDoi")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyDoi")
                        .IsUnique();

                    b.ToTable("QuyDoi");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTramGiamGia")
                        .HasColumnType("real");

                    b.Property<float>("SoTiemGiamGia")
                        .HasColumnType("real");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamGia")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSize")
                        .HasColumnType("int");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSize")
                        .IsUnique();

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0ed01b-6309-41a3-985f-ae02df9c56cc"),
                            MaSize = "SZ1",
                            SoSize = 30,
                            TenSize = "Size 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("566b0322-5d38-40cf-ab89-71d29da26a97"),
                            MaSize = "SZ2",
                            SoSize = 31,
                            TenSize = "Size 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("71536848-3988-446e-9a24-b3590dd95471"),
                            MaSize = "SZ3",
                            SoSize = 32,
                            TenSize = "Size 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("547a2588-be59-4d4c-b9e4-d5b47ba84fdb"),
                            MaSize = "SZ4",
                            SoSize = 33,
                            TenSize = "Size 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("8a45dba6-0b3b-4590-8b6f-b9443b0ac608"),
                            MaSize = "SZ5",
                            SoSize = 34,
                            TenSize = "Size 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanCap");

                    b.HasIndex("MaTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.HasOne("A_DAL.Entities.ChieuCaoDeGiay", "IdChieuCaoDeGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdChieuCaoDeGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Giay", "IdGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HangGiay", "IdHangGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdHangGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Nsx", "IdNsxNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdNsx")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Size", "IdSizeNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSize")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChieuCaoDeGiayNavigation");

                    b.Navigation("IdGiayNavigation");

                    b.Navigation("IdHangGiayNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdNsxNavigation");

                    b.Navigation("IdSizeNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Sale", "IdSaleNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.PhuongThucThanhToan", "IdPhuongThucThanhToanNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdPhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdPhuongThucThanhToanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "KhachHang")
                        .WithOne("DiemTieuDung")
                        .HasForeignKey("A_DAL.Entities.DiemTieuDung", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("GiaoCas")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienTiepQuanNavigation")
                        .WithMany("GiaoCaTiepQuans")
                        .HasForeignKey("IdNhanVienTiepQuan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdNhanVienTiepQuanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.DiemTieuDung", "IdDiemTieuDungNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdDiemTieuDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.QuyDoi", "IdQuyDoiNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdQuyDoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdDiemTieuDungNavigation");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdQuyDoiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("A_DAL.Entities.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.CuaHang", "IdCuaHangNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCuaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChucVuNavigation");

                    b.Navigation("IdCuaHangNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("TheLoais")
                        .HasForeignKey("IdPhanCap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Navigation("ChiTietSales");

                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietThanhToans");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("DiemTieuDung")
                        .IsRequired();

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("GiaoCaTiepQuans");

                    b.Navigation("GiaoCas");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Navigation("ChiTietSales");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("TheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
