// <auto-generated />
using System;
using A_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADAL.Migrations
{
    [DbContext(typeof(NahidaShoesDbContext))]
    partial class NahidaShoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChieuCaoDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHangGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChieuCaoDeGiay");

                    b.HasIndex("IdGiay");

                    b.HasIndex("IdHangGiay");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdMauSac", "IdSize", "IdNsx", "IdHangGiay", "IdChieuCaoDeGiay", "IdGiay")
                        .IsUnique();

                    b.ToTable("ChiTietGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1130bb9d-79ca-4261-a0d9-75b8e5fe0017"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("34b26fee-0885-40ac-bf81-dd0f93afdb8c"),
                            IdGiay = new Guid("4d88d065-ad86-47e1-b2c3-0b8ab2ff1592"),
                            IdHangGiay = new Guid("93ab81b5-a030-4e01-8b85-a76c9b0c5454"),
                            IdMauSac = new Guid("89c7cb02-37ee-4089-b32f-a7f6b92059cd"),
                            IdNsx = new Guid("454e02fa-d4b1-484f-a909-e9a2b5d46113"),
                            IdSize = new Guid("e23b737a-4cb9-48a1-9de4-f281f4021602"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("bdad7daa-0d20-4760-9a36-a7a7d6f5550f"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("89e7a9bb-8201-4e1b-9b2e-504acd47b56c"),
                            IdGiay = new Guid("5b473be5-36cf-4d95-a51c-72902469940e"),
                            IdHangGiay = new Guid("d9358645-9a2d-467f-81c8-c753caab6f6c"),
                            IdMauSac = new Guid("89c7cb02-37ee-4089-b32f-a7f6b92059cd"),
                            IdNsx = new Guid("c113456f-2cf6-413c-a691-1a0289a98098"),
                            IdSize = new Guid("c73c043c-8cc7-4e9a-b73b-6aa416146e24"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("79dd0b44-fc0e-430d-b140-4ffb2c317800"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("22c36326-7a9d-4ed5-b559-55e4b592a016"),
                            IdGiay = new Guid("f7b3b6f2-9f7b-4850-8c93-e13501c6b4b9"),
                            IdHangGiay = new Guid("f8dd80b1-3609-49f7-9ab9-a88608065dd1"),
                            IdMauSac = new Guid("1aecded2-5133-413b-bfb6-435acc6a0521"),
                            IdNsx = new Guid("9ec29d3d-f9ca-42f0-8f24-edb95ef63adc"),
                            IdSize = new Guid("e23b737a-4cb9-48a1-9de4-f281f4021602"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ea2897c8-bb27-464b-8e94-9463e9d26dca"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("22c36326-7a9d-4ed5-b559-55e4b592a016"),
                            IdGiay = new Guid("8bc671df-9ccf-4242-b3b6-affb4738c4d9"),
                            IdHangGiay = new Guid("a99e9417-b72c-4e06-82f5-d6d2993202cf"),
                            IdMauSac = new Guid("1aecded2-5133-413b-bfb6-435acc6a0521"),
                            IdNsx = new Guid("31afec0a-7a6e-41ae-a539-6182e0b942cb"),
                            IdSize = new Guid("c73c043c-8cc7-4e9a-b73b-6aa416146e24"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("e043e7ab-4def-4472-9d25-b2cab43f21ff"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("89e7a9bb-8201-4e1b-9b2e-504acd47b56c"),
                            IdGiay = new Guid("ed0cbf68-2e3d-4f9e-9816-86f4bef5ea33"),
                            IdHangGiay = new Guid("a99e9417-b72c-4e06-82f5-d6d2993202cf"),
                            IdMauSac = new Guid("89c7cb02-37ee-4089-b32f-a7f6b92059cd"),
                            IdNsx = new Guid("c113456f-2cf6-413c-a691-1a0289a98098"),
                            IdSize = new Guid("3a2c0617-0f67-44be-aa83-11ae45a822ee"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("bb603dbd-91d9-4eb9-9d9f-535f97d298af"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("5040cc28-955f-4230-be2b-4256c64303a4"),
                            IdGiay = new Guid("8bc671df-9ccf-4242-b3b6-affb4738c4d9"),
                            IdHangGiay = new Guid("93ab81b5-a030-4e01-8b85-a76c9b0c5454"),
                            IdMauSac = new Guid("7aac7f2d-ef71-465d-931f-3c0d15dcdb7c"),
                            IdNsx = new Guid("31afec0a-7a6e-41ae-a539-6182e0b942cb"),
                            IdSize = new Guid("c0dc3e4c-9f31-4256-9748-ab8adb16e822"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("9fdd0149-bcb6-4c5d-9ba4-4dd106a0d6bd"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("89e7a9bb-8201-4e1b-9b2e-504acd47b56c"),
                            IdGiay = new Guid("4d88d065-ad86-47e1-b2c3-0b8ab2ff1592"),
                            IdHangGiay = new Guid("93ab81b5-a030-4e01-8b85-a76c9b0c5454"),
                            IdMauSac = new Guid("7aac7f2d-ef71-465d-931f-3c0d15dcdb7c"),
                            IdNsx = new Guid("9ec29d3d-f9ca-42f0-8f24-edb95ef63adc"),
                            IdSize = new Guid("c73c043c-8cc7-4e9a-b73b-6aa416146e24"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("f3365239-c279-4275-869c-d80098e288de"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("22c36326-7a9d-4ed5-b559-55e4b592a016"),
                            IdGiay = new Guid("4d88d065-ad86-47e1-b2c3-0b8ab2ff1592"),
                            IdHangGiay = new Guid("a99e9417-b72c-4e06-82f5-d6d2993202cf"),
                            IdMauSac = new Guid("7aac7f2d-ef71-465d-931f-3c0d15dcdb7c"),
                            IdNsx = new Guid("aff3c1fe-8b3d-4f25-8140-0c55f9166806"),
                            IdSize = new Guid("3a2c0617-0f67-44be-aa83-11ae45a822ee"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("1558f0d3-b5f5-4366-84e1-0ac8dac907ea"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("5040cc28-955f-4230-be2b-4256c64303a4"),
                            IdGiay = new Guid("8bc671df-9ccf-4242-b3b6-affb4738c4d9"),
                            IdHangGiay = new Guid("93ab81b5-a030-4e01-8b85-a76c9b0c5454"),
                            IdMauSac = new Guid("89c7cb02-37ee-4089-b32f-a7f6b92059cd"),
                            IdNsx = new Guid("454e02fa-d4b1-484f-a909-e9a2b5d46113"),
                            IdSize = new Guid("3a2c0617-0f67-44be-aa83-11ae45a822ee"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("6aa63de5-b949-422b-8220-6c9924dffc05"),
                            GiaBan = 10000f,
                            GiaNhap = 7000f,
                            IdChieuCaoDeGiay = new Guid("5040cc28-955f-4230-be2b-4256c64303a4"),
                            IdGiay = new Guid("f7b3b6f2-9f7b-4850-8c93-e13501c6b4b9"),
                            IdHangGiay = new Guid("075c7f8b-fd9a-4e8b-9e7e-962ff6272374"),
                            IdMauSac = new Guid("d5c0eebb-75e0-4fce-a5dc-a6c57dca3085"),
                            IdNsx = new Guid("aff3c1fe-8b3d-4f25-8140-0c55f9166806"),
                            IdSize = new Guid("560df63d-f264-43e2-a013-1ff453b5d648"),
                            SoLuongTon = 100,
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdChiTietGiay", "IdSale")
                        .IsUnique();

                    b.ToTable("ChiTietSale");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPhuongThucThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SoTienThanhToan")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdPhuongThucThanhToan");

                    b.ToTable("ChiTietThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTheLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTheLoai");

                    b.HasIndex("IdChiTietGiay", "IdTheLoai")
                        .IsUnique();

                    b.ToTable("ChiTietTheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichCo")
                        .HasColumnType("int");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKichCo")
                        .IsUnique();

                    b.ToTable("ChieuCaoDeGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5040cc28-955f-4230-be2b-4256c64303a4"),
                            KichCo = 1,
                            MaKichCo = "KC1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("22c36326-7a9d-4ed5-b559-55e4b592a016"),
                            KichCo = 2,
                            MaKichCo = "KC2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("89e7a9bb-8201-4e1b-9b2e-504acd47b56c"),
                            KichCo = 3,
                            MaKichCo = "KC3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a722f9bb-24a3-450e-9959-a3b4d6023090"),
                            KichCo = 4,
                            MaKichCo = "KC4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("34b26fee-0885-40ac-bf81-dd0f93afdb8c"),
                            KichCo = 5,
                            MaKichCo = "KC5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaChucVu")
                        .IsUnique();

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0163d679-37ed-49c3-9a49-5cd7553ad99e"),
                            MaChucVu = "CV1",
                            TenChucVu = "Nhân viên",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCuaHang")
                        .IsUnique();

                    b.ToTable("CuaHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccbcdfe0-116c-427b-ab0e-892c97f10af5"),
                            DiaChi = "Hà Nội",
                            MaCuaHang = "CH1",
                            TenCuaHang = "Cửa hàng 1",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaDiemTieuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("SoDiem")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.HasIndex("MaDiemTieuDung")
                        .IsUnique();

                    b.ToTable("DiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVienTiepQuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiaoCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("TienDuTru")
                        .HasColumnType("real");

                    b.Property<float>("TienLai")
                        .HasColumnType("real");

                    b.Property<float>("TienPhatSinh")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdNhanVienTiepQuan");

                    b.HasIndex("MaGiaoCa")
                        .IsUnique();

                    b.ToTable("GiaoCa");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiay")
                        .IsUnique();

                    b.ToTable("Giay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7b3b6f2-9f7b-4850-8c93-e13501c6b4b9"),
                            MaGiay = "G1",
                            TenGiay = "Giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("5b473be5-36cf-4d95-a51c-72902469940e"),
                            MaGiay = "G2",
                            TenGiay = "Giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("8bc671df-9ccf-4242-b3b6-affb4738c4d9"),
                            MaGiay = "G3",
                            TenGiay = "Giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("ed0cbf68-2e3d-4f9e-9816-86f4bef5ea33"),
                            MaGiay = "G4",
                            TenGiay = "Giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("4d88d065-ad86-47e1-b2c3-0b8ab2ff1592"),
                            MaGiay = "G5",
                            TenGiay = "Giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHangGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHangGiay")
                        .IsUnique();

                    b.ToTable("HangGiay");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93ab81b5-a030-4e01-8b85-a76c9b0c5454"),
                            MaHangGiay = "HG1",
                            TenHangGiay = "Hãng giày 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("f8dd80b1-3609-49f7-9ab9-a88608065dd1"),
                            MaHangGiay = "HG2",
                            TenHangGiay = "Hãng giày 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("075c7f8b-fd9a-4e8b-9e7e-962ff6272374"),
                            MaHangGiay = "HG3",
                            TenHangGiay = "Hãng giày 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("a99e9417-b72c-4e06-82f5-d6d2993202cf"),
                            MaHangGiay = "HG4",
                            TenHangGiay = "Hãng giày 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d9358645-9a2d-467f-81c8-c753caab6f6c"),
                            MaHangGiay = "HG5",
                            TenHangGiay = "Hãng giày 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiamGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhuongThucMua")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianShip")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<Guid>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdChiTietGiay", "IdHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaKhachHang")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = new Guid("503f0856-e024-4a15-93ec-9a9ac0cc2837"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH1",
                            NgaySinh = new DateTime(2022, 12, 2, 19, 44, 38, 20, DateTimeKind.Local).AddTicks(8542),
                            Sdt = "0385922775",
                            SoCCCD = "12345",
                            TenKhachHang = "Khách hàng 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("9ae3c140-06f7-42c4-b5cc-648760e6b7e8"),
                            DiaChi = "Hà Nội",
                            MaKhachHang = "KH2",
                            NgaySinh = new DateTime(2022, 12, 2, 19, 44, 38, 20, DateTimeKind.Local).AddTicks(8554),
                            Sdt = "0385922775",
                            SoCCCD = "01234",
                            TenKhachHang = "Khách hàng 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTriQuyDoi")
                        .HasColumnType("real");

                    b.Property<Guid>("IdDiemTieuDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdQuyDoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDiemTieuDung");

                    b.HasIndex("IdQuyDoi");

                    b.HasIndex("IdHoaDon", "IdDiemTieuDung", "IdQuyDoi")
                        .IsUnique();

                    b.ToTable("LichSuDiemTieuDung");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaMauSac")
                        .IsUnique();

                    b.ToTable("MauSac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1aecded2-5133-413b-bfb6-435acc6a0521"),
                            MaMauSac = "MS1",
                            TenMauSac = "Màu sắc 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("d5c0eebb-75e0-4fce-a5dc-a6c57dca3085"),
                            MaMauSac = "MS2",
                            TenMauSac = "Màu sắc 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("89c7cb02-37ee-4089-b32f-a7f6b92059cd"),
                            MaMauSac = "MS3",
                            TenMauSac = "Màu sắc 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c87ad6da-56be-473a-bc2f-24e93d16dce0"),
                            MaMauSac = "MS4",
                            TenMauSac = "Màu sắc 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("7aac7f2d-ef71-465d-931f-3c0d15dcdb7c"),
                            MaMauSac = "MS5",
                            TenMauSac = "Màu sắc 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<Guid>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCuaHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.HasIndex("IdCuaHang");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94206fb7-b116-4f14-af38-4afd3aaf0385"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 0,
                            IdChucVu = new Guid("0163d679-37ed-49c3-9a49-5cd7553ad99e"),
                            IdCuaHang = new Guid("ccbcdfe0-116c-427b-ab0e-892c97f10af5"),
                            MaNhanVien = "NV1",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 12, 2, 19, 44, 38, 20, DateTimeKind.Local).AddTicks(8493),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("6dece21b-1005-4c79-8fbd-23ae322117ec"),
                            DiaChi = "Hà Nội",
                            GioiTinh = 1,
                            IdChucVu = new Guid("0163d679-37ed-49c3-9a49-5cd7553ad99e"),
                            IdCuaHang = new Guid("ccbcdfe0-116c-427b-ab0e-892c97f10af5"),
                            MaNhanVien = "NV2",
                            MatKhau = "00000",
                            NgaySinh = new DateTime(2022, 12, 2, 19, 44, 38, 20, DateTimeKind.Local).AddTicks(8514),
                            Sdt = "0385922775",
                            TenNhanVien = "Nhân viên 2",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNsx")
                        .IsUnique();

                    b.ToTable("Nsx");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ec29d3d-f9ca-42f0-8f24-edb95ef63adc"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX1",
                            TenNsx = "Nhà sản xuất 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("aff3c1fe-8b3d-4f25-8140-0c55f9166806"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX2",
                            TenNsx = "Nhà sản xuất 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("31afec0a-7a6e-41ae-a539-6182e0b942cb"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX3",
                            TenNsx = "Nhà sản xuất 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("454e02fa-d4b1-484f-a909-e9a2b5d46113"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX4",
                            TenNsx = "Nhà sản xuất 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c113456f-2cf6-413c-a691-1a0289a98098"),
                            DiaChi = "Hà Nội",
                            MaNsx = "NSX5",
                            TenNsx = "Nhà sản xuất 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQuyDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TiLeQuyDoi")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyDoi")
                        .IsUnique();

                    b.ToTable("QuyDoi");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTramGiamGia")
                        .HasColumnType("real");

                    b.Property<float>("SoTiemGiamGia")
                        .HasColumnType("real");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamGia")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSize")
                        .HasColumnType("int");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSize")
                        .IsUnique();

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0dc3e4c-9f31-4256-9748-ab8adb16e822"),
                            MaSize = "SZ1",
                            SoSize = 30,
                            TenSize = "Size 1",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("560df63d-f264-43e2-a013-1ff453b5d648"),
                            MaSize = "SZ2",
                            SoSize = 31,
                            TenSize = "Size 2",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("3a2c0617-0f67-44be-aa83-11ae45a822ee"),
                            MaSize = "SZ3",
                            SoSize = 32,
                            TenSize = "Size 3",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("e23b737a-4cb9-48a1-9de4-f281f4021602"),
                            MaSize = "SZ4",
                            SoSize = 33,
                            TenSize = "Size 4",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = new Guid("c73c043c-8cc7-4e9a-b73b-6aa416146e24"),
                            MaSize = "SZ5",
                            SoSize = 34,
                            TenSize = "Size 5",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanCap");

                    b.HasIndex("MaTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.HasOne("A_DAL.Entities.ChieuCaoDeGiay", "IdChieuCaoDeGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdChieuCaoDeGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Giay", "IdGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HangGiay", "IdHangGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdHangGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Nsx", "IdNsxNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdNsx")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Size", "IdSizeNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSize")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChieuCaoDeGiayNavigation");

                    b.Navigation("IdGiayNavigation");

                    b.Navigation("IdHangGiayNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdNsxNavigation");

                    b.Navigation("IdSizeNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietSale", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.Sale", "IdSaleNavigation")
                        .WithMany("ChiTietSales")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietThanhToan", b =>
                {
                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.PhuongThucThanhToan", "IdPhuongThucThanhToanNavigation")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("IdPhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdPhuongThucThanhToanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietTheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("ChiTietTheLoais")
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "KhachHang")
                        .WithOne("DiemTieuDung")
                        .HasForeignKey("A_DAL.Entities.DiemTieuDung", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("A_DAL.Entities.GiaoCa", b =>
                {
                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("GiaoCas")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienTiepQuanNavigation")
                        .WithMany("GiaoCaTiepQuans")
                        .HasForeignKey("IdNhanVienTiepQuan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdNhanVienTiepQuanNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.HasOne("A_DAL.Entities.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("A_DAL.Entities.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietGiay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.LichSuDiemTieuDung", b =>
                {
                    b.HasOne("A_DAL.Entities.DiemTieuDung", "IdDiemTieuDungNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdDiemTieuDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.HoaDon", "IdHoaDonNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.QuyDoi", "IdQuyDoiNavigation")
                        .WithMany("LichSuDiemTieuDungs")
                        .HasForeignKey("IdQuyDoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdDiemTieuDungNavigation");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdQuyDoiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("A_DAL.Entities.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_DAL.Entities.CuaHang", "IdCuaHangNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCuaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdChucVuNavigation");

                    b.Navigation("IdCuaHangNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.HasOne("A_DAL.Entities.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("TheLoais")
                        .HasForeignKey("IdPhanCap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("A_DAL.Entities.ChiTietGiay", b =>
                {
                    b.Navigation("ChiTietSales");

                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("A_DAL.Entities.ChieuCaoDeGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.CuaHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("A_DAL.Entities.DiemTieuDung", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Giay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HangGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietThanhToans");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("DiemTieuDung")
                        .IsRequired();

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.MauSac", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("GiaoCaTiepQuans");

                    b.Navigation("GiaoCas");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Entities.Nsx", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("A_DAL.Entities.QuyDoi", b =>
                {
                    b.Navigation("LichSuDiemTieuDungs");
                });

            modelBuilder.Entity("A_DAL.Entities.Sale", b =>
                {
                    b.Navigation("ChiTietSales");
                });

            modelBuilder.Entity("A_DAL.Entities.Size", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("A_DAL.Entities.TheLoai", b =>
                {
                    b.Navigation("ChiTietTheLoais");

                    b.Navigation("TheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
